#!/usr/bin/env bash
set -uo pipefail

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PATH_LINE="export PATH=\"\$PATH:$DIR/.bin\""
BASHRC="$HOME/.bashrc"

python3 -m venv $DIR/.venv
source $DIR/.venv/bin/activate
$DIR/.venv/bin/python3 -m pip install --ignore-installed --no-user $DIR
rm -rf -- "$DIR/build" "$DIR/dist" "$DIR"/*.egg-info "$DIR/.tmp"

mkdir $DIR/.bin
cp $DIR/anime-ultrascale $DIR/.bin
chmod +x "$DIR/.bin/anime-ultrascale"

grep -Fqx -- "$PATH_LINE" "$BASHRC" ||
    printf '\n%s\n' "$PATH_LINE" >> "$BASHRC"

source "$BASHRC"
