#!/usr/bin/env bash

################################################################################
# Program Directory
################################################################################

DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/.."

################################################################################
# File Deployment
################################################################################

mkdir $DIR/.bin
mkdir $DIR/.venv
mkdir $DIR/runner
mkdir $DIR/models
mkdir $DIR/sessions
mkdir $DIR/temp
mkdir $DIR/presets

cp $DIR/setup-files/launcher               $DIR/.bin/anime-ultrascale
cp $DIR/third-party/realesrgan-ncnn-vulkan $DIR/runner
cp $DIR/third-party/*.bin                  $DIR/models
cp $DIR/third-party/*.param                $DIR/models
cp $DIR/setup-files/*.preset               $DIR/presets

chmod +x $DIR/.bin/anime-ultrascale
chmod +x $DIR/runner/realesrgan-ncnn-vulkan

################################################################################
# Venv Creation
################################################################################

python3 -m venv $DIR/.venv
$DIR/.venv/bin/python3 -m pip install --ignore-installed --no-user $DIR
rm -rf -- "$DIR/build" "$DIR/dist" "$DIR"/*.egg-info "$DIR/.tmp"

################################################################################
# Bashrc Update
################################################################################

BASHRC="$HOME/.bashrc"
EXPORT="export PATH=\"\$PATH:$DIR/.bin\""

grep -Fqx -- "$EXPORT" "$BASHRC" || printf '\n%s\n' "$EXPORT" >> "$BASHRC"

################################################################################
# Bashrc Activation
################################################################################

source "$BASHRC"
